### PR TITLE
ci: add dockerfile for new pytorch versions

### PR DESCRIPTION
**Pull request by wangraying**
#652, as discussed with lightning team

### CODE REVIEW

**Comment by wangraying** [comment]
1.12 & 1.11 need further verified

**Comment by wangraying** [comment]
Verified: 1.13, 1.9

**Comment by wangraying** [comment]
@NOBLES5E   have tested these dockerfiles on local nodes (with bytegrad/mnist benchmark passed), could you please take a look and help me merge this PR?

**Review by woqidaideshi — APPROVED** [review]

**Comment by wangraying** [comment]
update lib path for the following error:

```
>>> import torch
>>> torch.cuda.device_count()
/opt/conda/lib/python3.8/site-packages/torch/cuda/__init__.py:82: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 34: CUDA driver is a stub library (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755903507/work/c10/cuda/CUDAFunctions.cpp:112.)
  return torch._C._cuda_getDeviceCount() > 0
0
```

**Pull request merged**
