### PR TITLE
fix: fix qadam NAN problem

### PR DESCRIPTION
**Pull request by wangraying**
fix https://github.com/BaguaSys/bagua/issues/485

### CODE REVIEW

**Comment by wangraying** [comment]
This pr is ready, please take a look.

**Comment by ganshaoduo** [comment]
I think maybe it's better to keep the 'weight_decay' and set it to 0 by default, for consistency with the original Adam optimizer.

**Comment by wangraying** [comment]
> I think maybe it's better to keep the 'weight_decay' and set it to 0 by default, for consistency with the original Adam optimizer.

Thanks @ganshaoduo , wondering how do we use `weight_decay` when calculating momentum, the relative code is [here](https://github.com/BaguaSys/bagua/blob/master/bagua/torch_api/algorithms/q_adam.py#L212).  The original paper does not discuss the situation with `weight_decay`, so I am not sure whether this will still converge in theory.

**Comment by ganshaoduo** [comment]
Well spotted! Actually, according to the current implementation, we only apply the 'weight_decay' in the warm-up phase but *not* in the compression phase. [This](https://github.com/BaguaSys/bagua/blob/master/bagua/torch_api/algorithms/q_adam.py#L88) change of `grad` is only counted `if step_id < self.warmup_steps`. However, when we calculate the momentum [here](https://github.com/BaguaSys/bagua/blob/master/bagua/torch_api/algorithms/q_adam.py#L210), the 'weight_decay' has been ignored.

About the necessity of "weight_decay", I would say it does not have a direct impact on the convergence. All it does is to add a small value to the gradient, which won't hurt the theoretical analysis of Qadam in my view.

Therefore, the question here is whether we add the 'weight_decay' operation [here](https://github.com/BaguaSys/bagua/blob/master/bagua/torch_api/algorithms/q_adam.py#L210) such that we use the same weight decay during both warm-up and compression phases, OR we delete the weight_decay operation [here](https://github.com/BaguaSys/bagua/blob/master/bagua/torch_api/algorithms/q_adam.py#L88) such that we do not consider the weight decay at all. I would prefer the former.

**Comment by wangraying** [comment]
> 

Thanks for your detailed explanations, Shaoduo. Yes, I added `weight_decay` using the first way you mentioned, but the performance drops on the synthetic benchmark. Since this pr is for fixing NAN problem for QAdam, how about we removing `weight_decay` temporarily here but adding an issue about this. We could add it back when it is totally prepared after more validations.

**Comment by wangraying** [comment]
The current implementation of `weight_decay` is added by me last time during refactoring. Our version #0 does not have this `weight_decay`. And we have not used it in our benchmarks and published results. Or do you think keep current implementation unchanged before further investigation is a good idea?

**Comment by wangraying** [comment]
After discussions offline, we decided to rollback the modifications for `weight_decay`.

**Pull request merged**
